### ISSUE TITLE
sample1 and sample2 entries?

### ISSUE THREAD

**Issue by drneavin** [Sandalmoth/ratrack#1]
Hi,

I am curious to try our ratrack but I can't understand what sample1 and sample2 entries should be. I've looked at the description in the manuscript and also on the github instructions but I still don't fully understand. For my experiment I have a cell line counted at four timepoints with triplicates at each timepoint so the 'name', 'time' and 'count' entries are quite clear to me but I was wondering if you could provide a bit more explanation on the sample1 and sample2 entries?

Thanks!

**Comment by Sandalmoth** [comment]
Hi!

The idea is that sample1 and sample2 (and I believe sample3, 4, 5... though it's been a while since I tested that) is to convert counts in the small volume that is actually counted, to a count for the entire cell population.

For example, looking at the top of the k562.csv file, we have:

name | time | count | dead | sample1 | sample2 | dilute1
-- | -- | -- | -- | -- | -- | --
K562.t0 | 0 | 61 | 5 | 0.001 | 0.02 | 0.0351

The way this data was collected experimentally, we had:
- 10 mL of cell culture, from which 10 uL was transferred to an eppendorf (sample1: 10uL/10mL = 0.001)
- 10 uL trypan blue was then added to the eppendorf, and the mixture was transferred to a haemocytometer slide
- cells in a grid cell was counted, and the volume of that grid cell was 0.4 uL (sample2: 0.4 uL/20uL = 0.02)

So, to get the number of cells in the whole culture, we have simply 61/(0.001*0.02) = 3.05e6. In other words, they describe the calculation required to get the number of cells in the culture from a small counted sample.

The reason why these steps are listed in this way, is because every time a cell culture is sampled we get some noise. Intuitively, you're unlikely to get exactly 1:1000th of the cells from taking 1:1000th of the volume. So to model that noise, the sampling data is needed.

I hope that clarifies it.

#### Sidenotes
It should be possible to use only one column (so just sample1), though my experiments weren't set up like that. Similarly, adding more steps should work as well.

In practice, I think the results should be fairly similar if simplified by 
- using only one sampling step (i.e. setting sample1 = sample1*sample2 and removing sample2), or even 
- pre-calculating the number of cells for count (so entering 3.05e6) and setting sample1 to 1, and removing sample 2. 
Though, there may be side effects from simplifying like that, it's hard to say.

**Comment by drneavin** [comment]
Thanks @Sandalmoth! That explanation was very helpful. I was originally using the pre-calculated numbers but updated to using the actual hemocytometer counts with sample1 and sample2 in the end and the growth rate estimates were much better.
